"""adding all tables

Revision ID: b092ceb663d0
Revises: 
Create Date: 2025-11-23 14:45:50.778525+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b092ceb663d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Admin',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Admin_email'), 'Admin', ['email'], unique=False)
    op.create_table('auth_providers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_name', sa.String(length=200), nullable=False),
    sa.Column('provider_type', sa.String(length=100), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.CHAR(length=2), nullable=True),
    sa.Column('phone_code', sa.CHAR(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_code'), 'countries', ['code'], unique=True)
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('Vegetables', 'Protein', 'Dairy', 'Grains', name='ingredienttype'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('emoji', sa.CHAR(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_name'), 'ingredients', ['name'], unique=False)
    op.create_index(op.f('ix_ingredients_type'), 'ingredients', ['type'], unique=False)
    op.create_table('meals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meal_type', sa.Enum('BREAKFAST', 'BRUNCH', 'ELEVENSES', 'LUNCH', 'AFTERNOON_TEA', 'HIGH_TEA', 'DINNER', 'SUPPER', 'MIDNIGHT_SNACK', name='mealtype'), nullable=False),
    sa.Column('icon', sa.CHAR(length=4), nullable=True),
    sa.Column('meal_name', sa.String(length=200), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meals_meal_name'), 'meals', ['meal_name'], unique=False)
    op.create_index(op.f('ix_meals_meal_type'), 'meals', ['meal_type'], unique=False)
    op.create_table('cities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_country_id'), 'cities', ['country_id'], unique=False)
    op.create_index(op.f('ix_cities_name'), 'cities', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_pic', sa.String(length=1024), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone_no', sa.String(length=32), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('calories_target', sa.Integer(), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_creator', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_city_id'), 'users', ['city_id'], unique=False)
    op.create_index(op.f('ix_users_country_id'), 'users', ['country_id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('admin_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('admin_id', sa.String(length=36), nullable=True),
    sa.Column('sender', sa.Enum('User', 'Admin', name='adminmessagesender'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['Admin.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_messages_admin_id'), 'admin_messages', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_messages_user_id'), 'admin_messages', ['user_id'], unique=False)
    op.create_table('creator_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('overview', sa.Text(), nullable=False),
    sa.Column('cooking_time', sa.Integer(), nullable=False),
    sa.Column('cuisine_type', sa.String(length=200), nullable=False),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=1024), nullable=True),
    sa.Column('ingredients', sa.JSON(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('action_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action_by', sa.String(length=36), nullable=True),
    sa.Column('action_comments', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='creatorpoststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['action_by'], ['Admin.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creator_posts_user_id'), 'creator_posts', ['user_id'], unique=False)
    op.create_table('creator_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('about_self', sa.Text(), nullable=False),
    sa.Column('experience', sa.Text(), nullable=False),
    sa.Column('links', sa.JSON(), nullable=True),
    sa.Column('requested_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('action_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action_by', sa.String(length=36), nullable=True),
    sa.Column('action_comments', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'DEACTIVE', name='creatorrequeststatus'), nullable=False),
    sa.ForeignKeyConstraint(['action_by'], ['Admin.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creator_requests_user_id'), 'creator_requests', ['user_id'], unique=False)
    op.create_table('follows',
    sa.Column('following_user_id', sa.String(length=36), nullable=False),
    sa.Column('followed_user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['followed_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('following_user_id', 'followed_user_id'),
    sa.UniqueConstraint('following_user_id', 'followed_user_id', name='uix_user_follows')
    )
    op.create_table('meal_planner',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('week_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=100), nullable=False),
    sa.Column('is_marked_done', sa.Boolean(), nullable=True),
    sa.Column('is_custom_meal', sa.Boolean(), nullable=True),
    sa.Column('meal_id', sa.Integer(), nullable=True),
    sa.Column('custom_meal_name', sa.String(length=255), nullable=True),
    sa.Column('custom_calories', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_planner_date'), 'meal_planner', ['date'], unique=False)
    op.create_index(op.f('ix_meal_planner_user_id'), 'meal_planner', ['user_id'], unique=False)
    op.create_index(op.f('ix_meal_planner_week_id'), 'meal_planner', ['week_id'], unique=False)
    op.create_table('user_auth_identities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone_no', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=512), nullable=True),
    sa.Column('access_token', sa.String(length=2048), nullable=True),
    sa.Column('refresh_token', sa.String(length=2048), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['auth_providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_auth_identities_email'), 'user_auth_identities', ['email'], unique=False)
    op.create_index(op.f('ix_user_auth_identities_provider_id'), 'user_auth_identities', ['provider_id'], unique=False)
    op.create_index(op.f('ix_user_auth_identities_user_id'), 'user_auth_identities', ['user_id'], unique=False)
    op.create_table('user_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('recevier_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['recevier_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_messages_recevier_id'), 'user_messages', ['recevier_id'], unique=False)
    op.create_index(op.f('ix_user_messages_sender_id'), 'user_messages', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_messages_sender_id'), table_name='user_messages')
    op.drop_index(op.f('ix_user_messages_recevier_id'), table_name='user_messages')
    op.drop_table('user_messages')
    op.drop_index(op.f('ix_user_auth_identities_user_id'), table_name='user_auth_identities')
    op.drop_index(op.f('ix_user_auth_identities_provider_id'), table_name='user_auth_identities')
    op.drop_index(op.f('ix_user_auth_identities_email'), table_name='user_auth_identities')
    op.drop_table('user_auth_identities')
    op.drop_index(op.f('ix_meal_planner_week_id'), table_name='meal_planner')
    op.drop_index(op.f('ix_meal_planner_user_id'), table_name='meal_planner')
    op.drop_index(op.f('ix_meal_planner_date'), table_name='meal_planner')
    op.drop_table('meal_planner')
    op.drop_table('follows')
    op.drop_index(op.f('ix_creator_requests_user_id'), table_name='creator_requests')
    op.drop_table('creator_requests')
    op.drop_index(op.f('ix_creator_posts_user_id'), table_name='creator_posts')
    op.drop_table('creator_posts')
    op.drop_index(op.f('ix_admin_messages_user_id'), table_name='admin_messages')
    op.drop_index(op.f('ix_admin_messages_admin_id'), table_name='admin_messages')
    op.drop_table('admin_messages')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index(op.f('ix_users_country_id'), table_name='users')
    op.drop_index(op.f('ix_users_city_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_cities_name'), table_name='cities')
    op.drop_index(op.f('ix_cities_country_id'), table_name='cities')
    op.drop_table('cities')
    op.drop_index(op.f('ix_meals_meal_type'), table_name='meals')
    op.drop_index(op.f('ix_meals_meal_name'), table_name='meals')
    op.drop_table('meals')
    op.drop_index(op.f('ix_ingredients_type'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_name'), table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_index(op.f('ix_countries_code'), table_name='countries')
    op.drop_table('countries')
    op.drop_table('auth_providers')
    op.drop_index(op.f('ix_Admin_email'), table_name='Admin')
    op.drop_table('Admin')
    # ### end Alembic commands ###
