"""Add food_preference and last_active to User

Revision ID: 42618e0e87b2
Revises: b092ceb663d0
Create Date: 2026-06-10 08:57:07.974146+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42618e0e87b2'
down_revision = 'b092ceb663d0'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('food_preference', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('last_active', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_active')
    op.drop_column('users', 'food_preference')
    # ### end Alembic commands ###
